/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.JOptionPane;

/**
 *
 * @author Haroon
 */
public class GamePanel extends javax.swing.JPanel {

    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        showInfoLabel = new javax.swing.JLabel();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel9.setOpaque(true);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        showInfoLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        showInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showInfoLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        showInfoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        showInfoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(showInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setInfoText()
    {
        if(MainWindow.player == 1)
        {
            showInfoLabel.setText("Single Player Game");
        }
        else
        {
            showInfoLabel.setText("Two Players Game");
        }
    }
    
    public void reset()
    {
        jLabel1.setText("");
        jLabel2.setText("");
        jLabel3.setText("");
        jLabel4.setText("");
        jLabel5.setText("");
        jLabel6.setText("");
        jLabel7.setText("");
        jLabel8.setText("");
        jLabel9.setText("");
        jLabel1.setEnabled(true);
        jLabel2.setEnabled(true);
        jLabel3.setEnabled(true);
        jLabel4.setEnabled(true);
        jLabel5.setEnabled(true);
        jLabel6.setEnabled(true);
        jLabel7.setEnabled(true);
        jLabel8.setEnabled(true);
        jLabel9.setEnabled(true);
        location1 = '1';
        location2 = '2';
        location3 = '3';
        location4 = '4';
        location5 = '5';
        location6 = '6';
        location7 = '7';
        location8 = '8';
        location9 = '9';
        Player = 1;
        number = 0;
        
    }

    private void setVals()
    {
        location1 = jLabel1.getText().charAt(0);
        location2 = jLabel2.getText().charAt(0);
        location3 = jLabel3.getText().charAt(0);
        location4 = jLabel4.getText().charAt(0);
        location5 = jLabel5.getText().charAt(0);
        location6 = jLabel6.getText().charAt(0);
        location7 = jLabel7.getText().charAt(0);
        location8 = jLabel8.getText().charAt(0);
        location9 = jLabel9.getText().charAt(0);
    }
    
    private int win()
    {
        if((location1 == location2 && location2 == location3) ||
        (location4 == location5 && location5 == location6) ||
        (location7 == location8 && location8 == location9) ||
        (location1 == location4 && location4 == location7) ||
        (location2 == location5 && location5 == location8) ||
        (location3 == location6 && location6 == location9) || 
        (location1 == location5 && location5 == location9) ||
        (location3 == location5 && location5 == location7) )
        { return 1; }
        else if (location1 != '1' && location2 != '2' && location3 != '3' 
                 && location4 != '4' && location5 != '5' && location6 != '6' 
                 && location7 != '7' && location8 != '8' && location9 != '9')
        {return 0; }
        else
        {return -1; }
    }
    
    private void inGame()
    {
        if(MainWindow.player == 1)
        {
            win();
            int decide = -1;
            fill = (Player == 1)? 'X' : 'O' ;
            
            if(Player == 1)
            {
                if ( number == 1 && location1 == '1' ) 
                { location1 = fill; jLabel1.setText(fill+""); }
                else if ( number == 2 && location2 == '2' ) 
                { location2 = fill; jLabel2.setText(fill+"");}
                else if ( number == 3 && location3 == '3' ) 
                { location3 = fill; jLabel3.setText(fill+"");}
                else if ( number == 4 && location4 == '4' ) 
                { location4 = fill; jLabel4.setText(fill+"");}
                else if ( number == 5 && location5 == '5' ) 
                { location5 = fill; jLabel5.setText(fill+"");}
                else if ( number == 6 && location6 == '6' ) 
                { location6 = fill; jLabel6.setText(fill+"");}
                else if ( number == 7 && location7 == '7' ) 
                { location7 = fill; jLabel7.setText(fill+"");}
                else if ( number == 8 && location8 == '8' ) 
                { location8 = fill; jLabel8.setText(fill+"");}
                else if ( number == 9 && location9 == '9' ) 
                { location9 = fill; jLabel9.setText(fill+"");}

                Player=2;
                decide = win();
                if ( decide == 1 )
                { 
                    int p = (Player==1)?2:1;
                    reset();
                    JOptionPane.showMessageDialog(null, "Congratulations!\nPlayer "+p+" Won!");

                }
                else if(decide == 0)
                {
                    reset();
                    JOptionPane.showMessageDialog(null, "GAME DRAW");

                }
            }
            if(Player == 2)
            {
                fill = 'O';
                if(MainWindow.mode == 'E')
                {
                    if ( location1 == '1')
                    {location1 = fill; jLabel1.setText(fill+"");jLabel1.setEnabled(false);}
                    else if ( location2 == '2')
                    {location2 = fill; jLabel2.setText(fill+"");jLabel2.setEnabled(false);}
                    else if ( location3 == '3')
                    {location3 = fill; jLabel3.setText(fill+"");jLabel3.setEnabled(false);}
                    else if ( location4 == '4')
                    {location4 = fill; jLabel4.setText(fill+"");jLabel4.setEnabled(false);}
                    else if ( location5 == '5')
                    {location5 = fill; jLabel5.setText(fill+"");jLabel5.setEnabled(false);}
                    else if ( location6 == '6')
                    {location6 = fill; jLabel6.setText(fill+"");jLabel6.setEnabled(false);}
                    else if ( location7 == '7')
                    {location7 = fill; jLabel7.setText(fill+"");jLabel7.setEnabled(false);}
                    else if ( location8 == '8')
                    {location8 = fill; jLabel8.setText(fill+"");jLabel8.setEnabled(false);}
                    else if ( location9 == '9')
                    {location9 = fill; jLabel9.setText(fill+"");jLabel9.setEnabled(false);}
                }
                else if(MainWindow.mode == 'M')
                {
                    if ( location1 =='X' && location2 == 'X' && location3 == '3')
                    { location3 = fill; jLabel3.setText(fill+""); jLabel3.setEnabled(false);}    
                    else if ( location2 =='X' && location3 == 'X' && location1 == '1')
                    { location1 = fill; jLabel1.setText(fill+""); jLabel1.setEnabled(false);}  
                    else if ( location1 =='X' && location3 == 'X' && location2 == '2')
                    { location2 = fill; jLabel2.setText(fill+""); jLabel2.setEnabled(false);}      
                    else if ( location5 =='X' && location6 == 'X' && location4 == '4')
                    { location4 = fill; jLabel4.setText(fill+""); jLabel4.setEnabled(false);}  
                    else if ( location4 =='X' && location6 == 'X' && location5 == '5')
                    { location5 = fill; jLabel5.setText(fill+""); jLabel5.setEnabled(false);}   
                    else if ( location8 =='X' && location9 == 'X' && location7 == '7')
                    { location7 = fill; jLabel7.setText(fill+""); jLabel7.setEnabled(false);}  
                    else if ( location7 =='X' && location9 == 'X' && location8 == '8')
                    { location8 = fill; jLabel8.setText(fill+""); jLabel8.setEnabled(false);}
                    else if ( location1 =='X' && location4 == 'X' && location7 == '7')
                    { location7 = fill; jLabel7.setText(fill+""); jLabel7.setEnabled(false);}    
                    else if ( location1 =='X' && location7 == 'X' && location4 == '4')
                    { location4 = fill; jLabel4.setText(fill+""); jLabel4.setEnabled(false);}  
                    else if ( location4 =='X' && location7 == 'X' && location1 == '1')
                    { location1 = fill; jLabel1.setText(fill+""); jLabel1.setEnabled(false);}
                    else if ( location2 =='X' && location5 == 'X' && location8 == '8')
                    { location8 = fill; jLabel8.setText(fill+""); jLabel8.setEnabled(false);}      
                    else if ( location2 =='X' && location8 == 'X' && location5 == '5')
                    { location5 = fill; jLabel5.setText(fill+""); jLabel5.setEnabled(false);}
                    else if ( location3 =='X' && location9 == 'X' && location6 == '6')
                    { location6 = fill; jLabel6.setText(fill+""); jLabel6.setEnabled(false);}       
                    else if ( location3 =='X' && location6 == 'X' && location9 == '9')
                    { location9 = fill; jLabel9.setText(fill+""); jLabel9.setEnabled(false);}
					else if ( location9 =='X' && location6 == 'X' && location3 == '9')
                    { location3 = fill; jLabel3.setText(fill+""); jLabel3.setEnabled(false);}
                    else if ( location1 =='X' && location5 == 'X' && location9 == '9')
                    { location9 = fill; jLabel9.setText(fill+""); jLabel9.setEnabled(false);}    
                    else if ( location5 =='X' && location9 == 'X' && location1 == '1')
                    { location1 = fill; jLabel1.setText(fill+""); jLabel1.setEnabled(false);}  
                    else if ( location1 =='X' && location9 == 'X' && location5 == '5')
                    { location5 = fill; jLabel5.setText(fill+"");jLabel5.setEnabled(false);}    
                    else if ( location5 =='X' && location7 == 'X' && location3 == '3')
                    { location3 = fill; jLabel3.setText(fill+""); jLabel3.setEnabled(false);}  
                    else if ( location3 =='X' && location7 == 'X' && location5 == '5')
                    { location5 = fill; jLabel5.setText(fill+"");jLabel5.setEnabled(false);}
					else if ( location3 =='X' && location5 == 'X' && location7 == '5')
                    { location7 = fill; jLabel7.setText(fill+"");jLabel7.setEnabled(false);}
					else if ( location5 == '5')
                    {location5 = fill; jLabel5.setText(fill+"");jLabel5.setEnabled(false);}
                    else if ( location1 == '1')
                    {location1 = fill; jLabel1.setText(fill+"");jLabel1.setEnabled(false);}
                    else if ( location2 == '2')
                    {location2 = fill; jLabel2.setText(fill+"");jLabel2.setEnabled(false);}
                    else if ( location3 == '3')
                    {location3 = fill; jLabel3.setText(fill+"");jLabel3.setEnabled(false);}
                    else if ( location4 == '4')
                    {location4 = fill; jLabel4.setText(fill+"");jLabel4.setEnabled(false);}
                    else if ( location6 == '6')
                    {location6 = fill; jLabel6.setText(fill+"");jLabel6.setEnabled(false);}
                    else if ( location7 == '7')
                    {location7 = fill; jLabel7.setText(fill+"");jLabel7.setEnabled(false);}
                    else if ( location8 == '8')
                    {location8 = fill; jLabel8.setText(fill+"");jLabel8.setEnabled(false);}
                    else if ( location9 == '9')
                    {location9 = fill; jLabel9.setText(fill+"");jLabel9.setEnabled(false);}
                }
                else if(MainWindow.mode == 'H')
                {
                    if ( location1 =='X' && location2 == 'X' && location3 == '3')
                    { location3 = fill; jLabel3.setText(fill+""); jLabel3.setEnabled(false);}    
                    else if ( location2 =='X' && location3 == 'X' && location1 == '1')
                    { location1 = fill; jLabel1.setText(fill+""); jLabel1.setEnabled(false);}  
                    else if ( location1 =='X' && location3 == 'X' && location2 == '2')
                    { location2 = fill; jLabel2.setText(fill+""); jLabel2.setEnabled(false);}  
                    else if ( location4 =='X' && location5 == 'X' && location6 == '6')
                    { location6 = fill; jLabel6.setText(fill+""); jLabel6.setEnabled(false);}    
                    else if ( location5 =='X' && location6 == 'X' && location4 == '4')
                    { location4 = fill; jLabel4.setText(fill+""); jLabel4.setEnabled(false);}  
                    else if ( location4 =='X' && location6 == 'X' && location5 == '5')
                    { location5 = fill; jLabel5.setText(fill+""); jLabel5.setEnabled(false);} 
                    else if ( location7 =='X' && location8 == 'X' && location9 == '9')
                    { location9 = fill; jLabel9.setText(fill+""); jLabel9.setEnabled(false);}    
                    else if ( location8 =='X' && location9 == 'X' && location7 == '7')
                    { location7 = fill; jLabel7.setText(fill+""); jLabel7.setEnabled(false);}  
                    else if ( location7 =='X' && location9 == 'X' && location8 == '8')
                    { location8 = fill; jLabel8.setText(fill+""); jLabel8.setEnabled(false);}
                    else if ( location1 =='X' && location4 == 'X' && location7 == '7')
                    { location7 = fill; jLabel7.setText(fill+""); jLabel7.setEnabled(false);}    
                    else if ( location1 =='X' && location7 == 'X' && location4 == '4')
                    { location4 = fill; jLabel4.setText(fill+""); jLabel4.setEnabled(false);}  
                    else if ( location4 =='X' && location7 == 'X' && location1 == '1')
                    { location1 = fill; jLabel1.setText(fill+""); jLabel1.setEnabled(false);}
                    else if ( location2 =='X' && location5 == 'X' && location8 == '8')
                    { location8 = fill; jLabel8.setText(fill+""); jLabel8.setEnabled(false);}    
                    else if ( location5 =='X' && location8 == 'X' && location2 == '2')
                    { location2 = fill; jLabel2.setText(fill+""); jLabel2.setEnabled(false);}  
                    else if ( location2 =='X' && location8 == 'X' && location5 == '5')
                    { location5 = fill; jLabel5.setText(fill+""); jLabel5.setEnabled(false);}
                    else if ( location3 =='X' && location9 == 'X' && location6 == '6')
                    { location6 = fill; jLabel6.setText(fill+""); jLabel6.setEnabled(false);}
                    else if ( location9 =='X' && location6 == 'X' && location3 == '3')
                    { location3 = fill; jLabel3.setText(fill+""); jLabel3.setEnabled(false);}  
                    else if ( location3 =='X' && location6 == 'X' && location9 == '9')
                    { location9 = fill; jLabel9.setText(fill+""); jLabel9.setEnabled(false);}
                    else if ( location1 =='X' && location5 == 'X' && location9 == '9')
                    { location9 = fill; jLabel9.setText(fill+""); jLabel9.setEnabled(false);}    
                    else if ( location5 =='X' && location9 == 'X' && location1 == '1')
                    { location1 = fill; jLabel1.setText(fill+""); jLabel1.setEnabled(false);}  
                    else if ( location1 =='X' && location9 == 'X' && location5 == '5')
                    { location5 = fill; jLabel5.setText(fill+"");jLabel5.setEnabled(false);}   
                    else if ( location3 =='X' && location5 == 'X' && location7 == '7')
                    { location7 = fill; jLabel7.setText(fill+""); jLabel7.setEnabled(false);}    
                    else if ( location5 =='X' && location7 == 'X' && location3 == '3')
                    { location3 = fill; jLabel3.setText(fill+""); jLabel3.setEnabled(false);}  
                    else if ( location3 =='X' && location7 == 'X' && location5 == '5')
                    { location5 = fill; jLabel5.setText(fill+""); jLabel5.setEnabled(false);}
					else if ( location5 == '5')
                    {location5 = fill; jLabel5.setText(fill+"");jLabel5.setEnabled(false);}
                    else if ( location1 == '1')
                    {location1 = fill; jLabel1.setText(fill+"");jLabel1.setEnabled(false);}
                    else if ( location2 == '2')
                    {location2 = fill; jLabel2.setText(fill+"");jLabel2.setEnabled(false);}
                    else if ( location3 == '3')
                    {location3 = fill; jLabel3.setText(fill+"");jLabel3.setEnabled(false);}
                    else if ( location4 == '4')
                    {location4 = fill; jLabel4.setText(fill+"");jLabel4.setEnabled(false);}
                    else if ( location6 == '6')
                    {location6 = fill; jLabel6.setText(fill+"");jLabel6.setEnabled(false);}
                    else if ( location7 == '7')
                    {location7 = fill; jLabel7.setText(fill+"");jLabel7.setEnabled(false);}
                    else if ( location8 == '8')
                    {location8 = fill; jLabel8.setText(fill+"");jLabel8.setEnabled(false);}
                    else if ( location9 == '9')
                    {location9 = fill; jLabel9.setText(fill+"");jLabel9.setEnabled(false);}
                }
		Player=1;
		decide = win();
                
                if ( decide == 1 )
                { 
                    int p = (Player==1)?2:1;
                    reset();
                    JOptionPane.showMessageDialog(null, "Congratulations!\nPlayer "+p+" Won!");

                }
                else if(decide == 0)
                {
                    reset();
                    JOptionPane.showMessageDialog(null, "GAME DRAW");

                }
            }
            

            
        }
        else
        {
            win();
            int decide = -1;
            Player = (Player%2==1)?1:2;
            fill = (Player == 1)? 'X' : 'O' ;
            
            if ( number == 1 && location1 == '1' ) 
            { location1 = fill; jLabel1.setText(fill+""); }
            else if ( number == 2 && location2 == '2' ) 
            { location2 = fill; jLabel2.setText(fill+"");}
            else if ( number == 3 && location3 == '3' ) 
            { location3 = fill; jLabel3.setText(fill+"");}
            else if ( number == 4 && location4 == '4' ) 
            { location4 = fill; jLabel4.setText(fill+"");}
            else if ( number == 5 && location5 == '5' ) 
            { location5 = fill; jLabel5.setText(fill+"");}
            else if ( number == 6 && location6 == '6' ) 
            { location6 = fill; jLabel6.setText(fill+"");}
            else if ( number == 7 && location7 == '7' ) 
            { location7 = fill; jLabel7.setText(fill+"");}
            else if ( number == 8 && location8 == '8' ) 
            { location8 = fill; jLabel8.setText(fill+"");}
            else if ( number == 9 && location9 == '9' ) 
            { location9 = fill; jLabel9.setText(fill+"");}
            
            decide = win();
            Player++;
            
            if ( decide == 1 )
            { 
                int p = --Player;
                reset();
                JOptionPane.showMessageDialog(null, "Congratulations!\nPlayer "+p+" Won!");
                
            }
            else if(decide == 0)
            {
                reset();
                JOptionPane.showMessageDialog(null, "GAME DRAW");
                
            }
        }
    }
    
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        number = 1;
        inGame();
        jLabel1.setEnabled(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        number = 2;
        inGame();
        jLabel2.setEnabled(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        number = 3;
        inGame();
        jLabel3.setEnabled(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        number = 4;
        inGame();
        jLabel4.setEnabled(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        number = 5;
        inGame();
        jLabel5.setEnabled(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        number = 6;
        inGame();
        jLabel6.setEnabled(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        number = 7;
        inGame();
        jLabel7.setEnabled(false);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        number = 8;
        inGame();
        jLabel8.setEnabled(false);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        number = 9;
        inGame();
        jLabel9.setEnabled(false);
    }//GEN-LAST:event_jLabel9MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel showInfoLabel;
    // End of variables declaration//GEN-END:variables
    private char location1 = '1';
    private char location2 = '2';
    private char location3 = '3';
    private char location4 = '4';
    private char location5 = '5';
    private char location6 = '6';
    private char location7 = '7';
    private char location8 = '8';
    private char location9 = '9';
    private char fill;
    private int Player = 1, number = 0;
    

}
